services:
  permify:
    image: ghcr.io/permify/permify
    ports:
      - "3476:3476"
      - "3478:3478"
    volumes:
      - ./:/config
  db:
    image: postgres:latest
    restart: unless-stopped
    environment:
      - POSTGRES_HOST=localhost
      - POSTGRES_PORT=5432
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres